#!/bin/bash

if [[ $(command -v brew) == "" ]]; then
    echo "Installing Hombrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    echo "Updating Homebrew"
    brew update && brew upgrade
fi

## Install dependencies
echo "Checking dependencies..."
declare -a deps=("java" "htop" "nvm" "jq" "ffmpeg" "youtube-dl" "watch")
for i in "${deps[@]}"
do
	if [[ $(command -v $i) == "" ]]; then
		echo "Installing $i"
		brew install $i
	else
		echo "$i is already installed."
	fi
done

echo "Checking cask dependencies..."
declare -a caskdeps=("keepassxc" "dropbox" "microsoft-teams" "openvpn-connect" "docker" "vlc")
for i in "${caskdeps[@]}"
do
	if [[ $(command -v $i) == "" ]]; then
		echo "Installing $i"
		brew install --cask $i
	else
		echo "$i is already installed."
	fi
done

## not managed by homebrew, have to create .nvm dir manually on first install
if [ ! -d "$HOME/.nvm" ]; then
	echo "Creating nvm dir: $HOME/.nvm"
	mkdir $HOME/.nvm
fi